version: '3.9'
services:
  php-server:
    build: 
      context: ./
      dockerfile: ./dockerfile/php/Dockerfile
    ports:
      - "9080:8080"
    container_name: phpserver
    volumes:
      - ./:/var/www
    networks:
      blog-frontend_myblog-dev:
        ipv4_address: 192.168.2.4
  nginx-backend:
    build: 
      context: ./
      dockerfile: ./dockerfile/nginx/Dockerfile
    ports:
      - "90:80"
    container_name: nginx-backend
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d/
    networks:
      blog-frontend_myblog-dev:
        ipv4_address: 192.168.2.5
    volumes_from:
      - php-server
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/var/www/mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      blog-frontend_myblog-dev:
        ipv4_address: 192.168.2.6
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - ./redis:/var/www/redis
    networks:
      blog-frontend_myblog-dev:
        ipv4_address: 192.168.2.7
networks:
  blog-frontend_myblog-dev:
    # we use a network that we created on fronted compose file. external means use this network
    external: true
