version: '3.9'
services:
    app:
        build:
            context: ./
            dockerfile: ./dockerfile/php/Dockerfile
        ports:
            - "9080:8080"
        container_name: app
        volumes:
            - ./:/var/www
        networks:
            blog-frontend_myblog-dev:
                ipv4_address: 192.168.2.4
    web:
        build:
            context: ./
            dockerfile: ./dockerfile/nginx/Dockerfile
        ports:
            - "90:80"
        container_name: web
        volumes:
            - ./docker/nginx/conf.d:/etc/nginx/conf.d/
        networks:
            blog-frontend_myblog-dev:
                ipv4_address: 192.168.2.5
        volumes_from:
            - app
    db:
        image: mongo:latest
        ports:
            - 27017:27017
        volumes:
            - ./mongo:/var/www/mongo
        container_name: db
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=password
        networks:
            blog-frontend_myblog-dev:
                ipv4_address: 192.168.2.6
    cache:
        image: redis:latest
        ports:
            - '6379:6379'
        container_name: cache
        command: redis-server --save 20 1 --loglevel warning
        volumes:
            - ./redis:/var/www/redis
        networks:
            blog-frontend_myblog-dev:
                ipv4_address: 192.168.2.7
networks:
    blog-frontend_myblog-dev:
        # we use a network that we created on fronted compose file. external means use this network
        external: true
